const NewsActionTypes = {
  FETCH_NEWS_ITEM_START: "FETCH_NEWS_ITEM_START",
  FETCH_NEWS_ITEM_SUCCESS: "FETCH_NEWS_ITEM_SUCCESS",
  FETCH_NEWS_ITEM_FAILURE: "FETCH_NEWS_ITEM_FAILURE"
};

export default NewsActionTypes;
